name: Deploy to AWS Amplify
on:
  push:
    branches:
      - main  # or your default branch name if different
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
      - name: Build
        run: npm run build
        env:
          REACT_APP_USER_MICROSERVICE_URL: ${{ secrets.REACT_APP_USER_MICROSERVICE_URL }}
          REACT_APP_RESTAURANT_MICROSERVICE_URL: ${{ secrets.REACT_APP_RESTAURANT_MICROSERVICE_URL }}
          REACT_APP_AVAILABILITY_MICROSERVICE_URL: ${{ secrets.REACT_APP_AVAILABILITY_MICROSERVICE_URL }}